Branch v1.2b
AY2324S1-CS2103T-T10-1/tp pull request #39
Opened 2023-10-18 03:48 UTC by LuoZYi

Update hour field inside person class and relevant code and tests. Hour field should be bounded by [0, 9999] inclusive. Currently the edit function can only set the hour to a given value, and it could be developed into a new command to add hours or substract hours for individuals or for everyone.

2023-10-18 05:55 UTC, raynertjx requested changes
LGTM! Just some minor changes to the GUI.

2023-10-18 05:55 UTC, raynertjx commented on src/main/java/seedu/address/logic/commands/AddCommand.java
>              + "[" + PREFIX_MOD + "MOD]...\n"
I think we can remove the ...\n at the end, and just leave a single whitespace after the closing square bracket.

2023-10-18 13:59 UTC, LuoZYi commented on src/main/java/seedu/address/logic/commands/AddCommand.java
>              + "[" + PREFIX_MOD + "MOD]...\n"
fixed

2023-10-19 15:20 UTC, raynertjx approved these changes

2023-10-19 15:20 UTC, merged